#!/bin/bash
script_dir_path=`dirname $0`

create_app_alias () {
	echo $1
	echo "
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Go to $1
Exec=$script_dir_path/i3-go-to-app $1
	" > ~/.local/share/applications/go-to-$1.desktop
}
remove_app_alias () {
	rm ~/.local/share/applications/go-to-$1.desktop
}

apps=`i3-msg -t get_tree | jq '.nodes[].nodes[].nodes[].nodes[].window_properties.class' | sort -u | cut -d'"' -f 2`

for app in $apps; do
	create_app_alias $app
done

i3-dmenu-desktop

for app in $apps; do
	remove_app_alias $app
done
